# Generated by Django 3.2.16 on 2025-01-24 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20250124_2311'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favoriterecipe',
            name='unique_favorite_recipe',
        ),
    ]
